git-for-windows/MINGW-packages

- mingw-w64-git/PKGBUILD
When generating the `git` package for the `net-installer` to install the
*Git for Windows SDK* it should be best practice to append the short
`SHA1` of the current `HEAD` commit.
With this feature future developer can spot right on which development
state the current package was built on.
Signed-off-by: nalla <nalla@hamal.uberspace.de>
> mingw64-git: Add short `SHA1` to the version

- mingw-w64-asciidoctor-extensions/0001-man-inline-macro-enable-linkgit-syntax.patch
- mingw-w64-asciidoctor-extensions/PKGBUILD
- mingw-w64-asciidoctor-extensions/asciidoctor-extensions.install
This new package will install `asciidoctor` in the `pre_install` function.
The already available `man-inline-macro` is then patched to support the
`:linkgit` syntax and then installed in the appropiate lib directory.
Signed-off-by: nalla <nalla@hamal.uberspace.de>
> asciidoctor: bundle requirements to build git doc

- mingw-w64-git/PKGBUILD
This adds `mingw64/mingw-w64-x86_64-ca-certificates` and `mingw64/mingw-w64-x86_64-tk` (for `wish.exe`) as dependencies of the git package to the `PKGBUILD` file.
> Added missing dependencies to PKGBUILD file

- mingw-w64-git/start-ssh-agent.cmd
This does two things:
* remove printed parentheses due to missing '@'s (https://github.com/git-for-windows/git/issues/314)
* cleanup the env variables so that a restart-after-kill of the ssh-agent in an opened session (-> cmd) will cleanup the files. 
Closes: https://github.com/git-for-windows/git/issues/314
> Silence start ssh agent

- mingw-w64-git/PKGBUILD
When creating the `config.mak` to tell `make` to use asciidoctor `instead`
of `asciidoc`, lets make sure that we only quote the parts that needs it.
Quoting the full `ASCIIDOCTOR_CONF` variable is leading to a wrong
invocation of the `asciidoctor` command because then the different
asciidoctor options `-I` and `-r` are not being recognized.
This fixes https://github.com/git-for-windows/git/issues/404
> git: fix asciidoctor invocation

- mingw-w64-git/PKGBUILD
- mingw-w64-git/start-ssh-pageant.cmd
This pull request is a sibling of [this one against git-for-windows/build-extra](https://github.com/git-for-windows/build-extra/pull/109), which adds [ssh-pageant integration](https://github.com/git-for-windows/git/issues/683) to Git for Windows. The ssh-pageant utility is drop-in replacement for ssh-agent, which allows OpenSSH to authenticate using keys stored in the PuTTY authentication agent (Pageant). Basically it makes it easier to use OpenSSH within Git, for those of us using PuTTY outside of the Git for Windows project.
This 2 commits in question simply add a `start-ssh-pageant.cmd` script, based upon `start-ssh-agent.cmd`, and updates the associated PKGBUILD to include it in the mingw-w64-git package build.
I had previously added a Wiki entry on manual [OpenSSH Integration with …
> Add helper script for ssh-pageant integration

- mingw-w64-git/PKGBUILD
- mingw-w64-git/git-bash.rc
Currently git-bash relies on mintty options that were proposed in a pull
request. A mintty package was also build with these changes. However, the
proposed options were changed slightly when merged into the official
mintty.
Offical mintty uses AppLaunchCmd instead of RelaunchCommand, AppName
instead of RelaunchDisplayName and requires an additional option
--store-taskbar-properties for the options to take effect.
In addition to these changes, specifying the path for the icon as
/mingw64/share/git/git-for-windows.ico no longer works. Using
"@@EXEPATH@@\\mingw64\\share\\git\\git-for-windows.ico" works, however,
instead of relying on a separate file we can just as well get the icon
from our git-bash executable.
> mingw-w64-git: adjust git-bash to official mintty

- mingw-w64-curl/.gitignore
- mingw-w64-curl/PKGBUILD-winssl-bin.patch
- mingw-w64-curl/make-PKGBUILD-winssl-bin.sh
mingw-w64-curl-winssl-bin contains only binary files installed to /mingw64/bin/curl-winssl. The package depends on mingw-w64-curl which provides all the rest.
PKGBUILD-winssl-bin is generated from PKGBUILD with a patch file.
See discussion in the issue for more details: https://github.com/git-for-windows/git/issues/301
I don't run makepkg-mingw at the end of the script because `please.sh` uses more complex code:
```
"$sdk/git-cmd.exe" --command=usr\\bin\\sh.exe -l -c \
'MAKEFLAGS=-j5 MINGW_INSTALLS=mingw32\ mingw64 \
'"$extra"'makepkg-mingw -s --noconfirm &&
MINGW_INSTALLS=mingw64 makepkg-mingw --allsource' ||
die "%s: could not build\n" "$sdk/$pkgpath"
```
I think the code should be modified to use PKGBUILD scripts with various file names.
> mingw-w64-curl: add winssl-bin package configuration

- mingw-w64-git/git-wrapper.c
Support for git-lfs wrapping in `/cmd`, see git-for-windows/git#1503
> mingw-w64-git: add support to git-wrapper for wrapping git-lfs

- mingw-w64-git/PKGBUILD
- mingw-w64-git/mingw-w64-git.mak
Add mak file to build wrappers faster. It's a copy from MAKEPKG file: maybe it's easier to have only one copy of this text stored in the separate file?
I also created Wiki page, I guess it could be useful for other developers. I can't add it to Git For Windows project because it does not have Wiki at all, you can read it from my fork:
https://github.com/telezhnaya/MINGW-packages/wiki/FAQ:-Git-package
> Add mingw-w64-git.mak

- mingw-w64-git/git-wrapper.c
There were a couple of mistakes there, including restricting the maximal length of Git's top-level directory too much, causing https://github.com/git-for-windows/git/issues/1764
> git: fix the MAX_PATH handling of the Git wrapper

- mingw-w64-git/PKGBUILD
Let's offer a way to build `mingw-w64-git` without having Visual Studio installed.
> git: optionally build without PDBs

- mingw-w64-git/PKGBUILD
- mingw-w64-git/git-bash.txt
This adds a help page for the Git Bash command, but more importantly, it demonstrates how to add extra help pages in Git for Windows.
> git: provide a help page for `git-bash.exe`

- mingw-w64-git/PKGBUILD
@telezhnaya reported a long time ago that an initial build of the `mingw-w64-git` package fails, with an obscure error message that the empty `sha1collisiondetection` directory cannot be added.
Turns out that this happens while we want to make sure that Git is checked out with `core.autocrlf=false`, and the symptom is caused by a bug in `git stash`.
We do not _have_ to use `git stash`, so let's use `git reset --hard` instead.
> git: avoid problems with the sha1collisiondetection submodule

- mingw-w64-curl/PKGBUILD
cURL, starting with version 7.58, changed build settings around SSH support so that MinGW builds of cURL made since have scp and scftp protocols support disabled.
This commit re-enabled SSH support for MinGW builds.
PR for issue https://github.com/git-for-windows/git/issues/2491.
> mingw-w64-curl: Update PKGBUILD in order to build with libssh2.

- mingw-w64-git/PKGBUILD
- mingw-w64-git/edit-git-bash.c
- mingw-w64-git/git-wrapper.c
- mingw-w64-git/git.install
- mingw-w64-git/mingw-w64-git.mak
The main thrust of this PR is to allow telling Git Bash that the user wants to opt-in to the pseudo console support. With this PR, we allow doing that by writing `MSYS=enable_pcon` into `/etc/git-bash.config`.
This PR looks a bit more complicated than absolutely necessary because I slipped in two more things (because I wanted them for ages): by default, we now install the git/bash/sh redirectors into `/bin/` in the Git for Windows SDK (which will come in _real_ handy especially in automation, no more `git-cmd.exe --command=usr\bin\bash.exe` awkwardness), and we also include the `edit-git-bash` helper (because it makes the most sense, as `mingw-w64-git` owns `git-bash.exe`).
> git (git-bash): parse a file to opt-in to pseudo console support

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
This fixes https://github.com/git-for-windows/git/issues/3266
> Handle UNC paths correctly when making cURL relocatable

- .github/workflows/build-and-deploy.yml
This is the equivalent to https://github.com/git-for-windows/MSYS2-packages/blob/main/.github/workflows/build-and-deploy.yml, and was prepared in case we need it to build `mingw-w64-gettext` to be able to build Git for Windows v2.35.0-rc0.
We no longer need this _urgently_, but I open this PR anyway because it will provide a good starting point when we start transitioning Git for Windows' packaging process away from Azure Pipelines toward GitHub workflows (and probably also away from doing everything in `/usr/src/build-extra/please.sh upgrade <package>` toward a more PR-centric flow).
> Add a GitHub workflow to build and deploy a single MINGW package

- mingw-w64-git/PKGBUILD
As part of [some spring cleaning](https://github.com/git-for-windows/git-sdk-64/compare/b11327be14...0185b0666c) of the Git for Windows SDK, I noticed that we still had Python v2.x and AsciiDoc because they are listed as dependencies of `mingw-w64-git`. But we don't actually need them...
> git: do not depend on Python v2.x nor on AsciiDoc

- mingw-w64-xpdf/PKGBUILD
Apparently, xpdf has changed their download URLs. The old S3-based URL no longer works. Looking at their website (xpdfreader.com), it seems that their download domain is now dl.xpdfreader.com. Since the SHA256 of the file hasn't changed, we can consider this to be a safe change.
Signed-off-by: Dennis Ameling <dennis@dennisameling.com>
> mingw-w64-xpdf: fix source URL

- mingw-w64-git/git.install
This script was missing logic for the aarch64 architecture, resulting in the following [while experimenting](https://github.com/git-for-windows/git/discussions/4186#discussioncomment-4449439) with a `git-sdk-arm64`:
```
(1/1) installing mingw-w64-clang-aarch64-git                                 [##########################################] 100%
cp: cannot stat '/mingw64/share/git/compat-bash.exe': No such file or directory
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_2W08dr/.INSTALL; post_install 2.39.0.1.de9501c66f-1 ) failed to execute correctly
```
Since MSYS2 bash runs on x64 emulation on Windows arm64, we can't rely on `uname -m` for this architecture. Instead, let's leverage `$MINGW_PREFIX`, which is always set when `$MSYSTEM` is set.
Ref: …
> mingw-w64-git: fix git.install script on arm64

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/0002-Hack-make-relocation-work-inside-libexec-git-core-an.patch
- mingw-w64-curl/PKGBUILD
- mingw-w64-curl/pathtools.c
- mingw-w64-curl/pathtools.h
Years ago, I taught libcurl the trick to include multiple SSL/TLS backends, and then I taught Git for Windows to have a run-time option to choose between those. This allowed users relying on OpenSSL (e.g. because they read somewhere on the internet that you need OpenSSL to be able to access Git repositories on hosts with self-signed certificates) but also offering to rely on Secure Channel to handle https:// URLs.
However, this now comes back to bite me.
As per https://github.com/git-for-windows/git/issues/4350#issuecomment-1485041503, the major block for upgrading Git for Windows' OpenSSL from v1.1 to v3 is the tricky part where such an upgrade would break `git fetch`/`git clone` and `git push` because the libcurl depends on the OpenSSL DLL, and the major version bump will _change_ the …
> Align libcurl with MSYS2

- mingw-w64-git/PKGBUILD
- mingw-w64-git/mingw-w64-git.mak
Now that [the Git wrapper can impersonate `git-receive-pack.exe` when installed into `/cmd/`](https://github.com/git-for-windows/MINGW-packages/pull/85), redirecting to the actual executable, let's do so.
This allows Git for Windows to serve repositories via SSH when [running the corresponding Windows service](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration) as long as Git for Windows' `/cmd/` directory is in the `PATH`.
This fixes https://github.com/git-for-windows/git/issues/4359.
> git: offer `/cmd/git-receive.exe` and `git-upload-pack.exe`

- mingw-w64-git/PKGBUILD
- mingw-w64-git/git-wrapper.c
There is a long standing known issue in @dennisameling test builds
> When using the installer and selecting the "Add a Git Bash Profile to Windows Terminal" option, the profile is added to Windows Terminal, but it crashes on launch.
Turns out it's a caching issue.
> ARM64: fix `/bin/bash.exe` and `/bin/sh.exe` not starting

- .github/workflows/main.yml
GitHub released new versions of actions/checkout and actions/upload-artifact based on node20. Use these new versions to get rid of the warning that node16 is deprecated.
> ci: update actions to use node20

- mingw-w64-curl/PKGBUILD
The `git update-git-for-windows` command is a Unix Shell script that relies heavily on `curl`; For example, it calls:
curl --silent --show-error --output /tmp/gfw-httpget-ruMLqjGG.txt \
--write-out '%{http_code}' \
https://api.github.com/repos/git-for-windows/git/releases/latest
This worked well until cURL v8.8.0 was integrated. With the Secure Channel backend, the invocation would fail with this error message:
curl: (43) A libcurl function was given a bad argument
The same issue had been reported for a different SSL backend: https://github.com/curl/curl/issues/13845. Conveniently, all we have to do is to Backport the fix from the PR that addressed that ticket to address the bug at hand.
This fixes https://github.com/microsoft/git/issues/655.
> curl: fix `--write-out '%{http_code}'` with Secure Channel

- .github/workflows/main.yml
- mingw-w64-git/PKGBUILD
While enabling clangarm64 support on GfW's
`mingw-w64-asciidoctor-extensions` package, we realized that the
extensions are likely not needed anymore, because the Git project
added its own `Documentation/asciidoctor-extensions.rb` back in 2017.
Let's switch to the MSYS2-maintaned `mingw-w64-asciidoctor` instead,
so we don't have to maintain our own package anymore.
Ref: https://github.com/git-for-windows/MINGW-packages/pull/118
Ref: https://github.com/git/git/commit/55d2d812e49aece049b73682ad5980ea84e23839
Let's also enable arm64 support while we're at it.
> mingw-w64-git: switch to asciidoctor and enable arm64 for it

- .github/workflows/main.yml
- mingw-w64-git/git.install
Fix https://github.com/git-for-windows/git/issues/5067.
> mingw-w64-git: use /proc/cygdrive prefix in bin path when installing redirectors

- mingw-w64-curl/PKGBUILD
See https://github.com/curl/curl/issues/15496
and https://github.com/curl/curl/issues/15513
Cherry-picked from 8b1c7bde2 (curl: Fix regression reading netrc, 2024-11-11) in msys2/MINGW-packages.
This is a companion to https://github.com/git-for-windows/MSYS2-packages/pull/199, even if the problem did not affect the MINGW variant of `curl` in my case ([I have no `.netrc`](https://github.com/curl/curl/issues/15496#issuecomment-2460427486), yet the MSYS variant _was_ affected).
> curl: Fix regression reading netrc

- mingw-w64-curl/0003-ip-happy-do-not-set-unnecessary-timeout.patch
- mingw-w64-curl/PKGBUILD
In cURL v8.16.0, the behavior changed subtly: Timeouts were added even in circumstances where cURL failed to connect and should have errored out with the corresponding `CURLE_COULDNT_CONNECT` instead.
This has been identified [in `microsoft/git`](https://github.com/microsoft/git/pull/799#issuecomment-3346304034) via test failures in t5799:
```
++ test_when_finished per_test_cleanup
++ test 0 = 0
++ test_cleanup='{ per_test_cleanup
} && (exit "$eval_ret"); eval_ret=$?; :'
++ test_must_fail git -C 'D:/a/git/git/t/trash directory.t5799-gvfs-helper/repo_t1' gvfs-helper --cache-server=disable --remote=origin get --max-retries=2
++ case "$1" in
++ _test_ok=
++ test_must_fail_acceptable git -C 'D:/a/git/git/t/trash directory.t5799-gvfs-helper/repo_t1' gvfs-helper --cache-server=disable …
```
> Fix the cURL problem identified in `microsoft/git` via t5799.13(curl-connect: no server) failures
